config/routes.rb
Rails.application.routes.draw do

  resources :administrations
  resources :gams_paths
  resources :productions
  resources :consumptions
  resources :warehousings
  resources :orders
  resources :shipments
  resources :final_products
  resources :storages
  resources :months
  resources :suppliers
  resources :customers
  resources :rawoils
  resources :refineries

  get 'blending_start' => 'static_pages#blending_start'
  get 'customer_signup' => 'custom_customer#new_customer'
  get 'supplier_signup' => 'custom_supplier#new_supplier'
  post 'warehousings/read_and_show_ofv', :to => 'warehousings#read_and_show_ofv'
  post 'warehousings/read_optimization_results', :to => 'warehousings#read_optimization_results'
  post 'warehousings/optimize', :to => 'warehousings#optimize'
  post 'warehousings/delete_old_plan', :to => 'warehousings#delete_old_plan'
  post 'warehousings/show_index_page', :to => 'warehousings#show_index_page'



  post "periods/change", as: :change_periods

  resources :machine_period_associations
  resources :periods
  resources :product_period_associations
  resources :product_product_associations
  resources :machines
  resources :items
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites
  resources :products


  get 'transport_start', to: 'static_pages#transport_start'
  get 'mlclsp_start', to: 'static_pages#mlclsp_start'


  post 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  post 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  post 'product_periods/read_and_show_ofv', :to => 'product_period_associations#read_and_show_ofv'
  post 'product_periods/read_optimization_results', :to => 'product_period_associations#read_optimization_results'
  post 'product_periods/optimize', :to => 'product_period_associations#optimize'
  post 'product_periods/delete_old_plan', :to => 'product_period_associations#delete_old_plan'
  post 'product_periods/show_index_page', :to => 'product_period_associations#show_index_page'



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @customers = Customer.where(customers: {namefi: current_user.firstname, namela: current_user.name})
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Über uns") %> <h1>Über uns</h1> <p> Diese Homepage beschäftigt sich im Rahmen der Vorlesung "Entwicklung
  von Anwendungssystemen" bei Herrn Professor Helber mit dem "Blending of Oil-Problem". Auf der Basis des
  <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorials</em></a> von Michael Hartl wird eine
  Web-Applikation zur betriebswirtschaftlichen Entscheidungsunterstützung erstellt, die als Illustration für die Lösung
  unterschiedlicher Planungsprobleme des Operations Managements dient. Über verschiedene Links können hierbei die
  jeweiligen Parameter eingegeben und verwaltet werden. Nachdem die Optimierung gestartet wurde, können über weitere
  Links die optimalen Rohölverbräuche und -bestände sowie die Produktionsmengen und der optimale Gewinn eingelesen
  werden.
</p>

app/views/static_pages/blending_start.html.erb
<% provide(:title, 'Blending of Oil - App') %>

<h1>Blending of Oil</h1>

<br>

<div class="linkcontainer">
  <div class="centerwrapper">

    <% if can? :index, Rawoil %>
        <div class="image">
          <%= link_to image_tag('rawoil.png', height: '50', alt: 'Rohöl logo'), rawoils_path %> <br>
          <%= link_to 'Verwaltung der Rohöle', rawoils_path %>
        </div>
    <% end %>


    <% if can? :index, Refinery %>
        <div class="image">
          <%= link_to image_tag('Raffinerie.png', height: '50', alt: 'Raffinerie logo'), refineries_path %><br>
          <%= link_to 'Verwaltung der Raffinerien', refineries_path %>
        </div>
    <% end %>


    <% if can? :index, Storage %>
        <div class="image">
          <%= link_to image_tag('Lagertank.png', height: '50', alt: 'Lagertank logo'), storages_path %><br>
          <%= link_to 'Verwaltung der Lagertanks', storages_path %>
        </div>
    <% end %>

    <% if can? :index, FinalProduct %>
        <div class="image">
          <%= link_to image_tag("Endprodukt.png", height: '50', alt: 'Endprodukt logo'), final_products_path %><br>
          <%= link_to 'Verwaltung der Endprodukte', final_products_path %>
        </div>
    <% end %>


    <% if can? :index, Customer %>
        <div class="image">
          <%= link_to image_tag('customers1.png', height: '50', alt: 'Kunde logo'), customers_path %><br>
          <%= link_to 'Verwaltung der Kunden', customers_path %>
        </div>
    <% end %>


    <% if can? :index, Order %>
        <div class="image">
          <%= link_to image_tag("shopping_cart-512.png", height: '50', alt:"Kundenbestellung logo"), orders_path %><br>
          <%= link_to 'Verwaltung der Kundenbestellungen', orders_path %> <br>
        </div>
    <% end %>


    <% if can? :index, Month %>
        <div class="image">
          <%= link_to image_tag("month.png", height: '50', alt:"Monat logo"), months_path %><br>
          <%= link_to "Verwaltung der Monate", months_path %><br>
        </div>
    <% end %>


    <% if can? :index, Supplier %>
        <div class="image">
          <%= link_to image_tag('Lieferant.png', height: '50', alt: 'Lieferant logo'), suppliers_path %><br>
          <%= link_to 'Verwaltung der Lieferanten', suppliers_path %><br>
        </div>
    <% end %>


    <% if can? :index, Shipment %>
        <div class="image">
          <%= link_to image_tag("shipment.png", height: '50', alt:"Lieferung logo"), shipments_path %><br>
          <%= link_to 'Verwaltung der Rohöhllieferungen', shipments_path %> <br>
        </div>
    <% end %>


    <% if can? :index, Consumption %>
        <div class="image">
          <%= link_to image_tag("rohoelverbrauch.png", height: '50', alt:"Rohölverbrauch logo"), consumptions_path %><br>
          <%= link_to 'Anzeige der Rohölverbräuche', consumptions_path %> <br>
        </div>
    <% end %>


    <% if can? :index, Production %>
        <div class="image">
          <%= link_to image_tag("Produktionsmenge.png", height: '50', alt:"Produktionsmenge logo"), productions_path %><br>
          <%= link_to 'Anzeige der Produktionsmengen', productions_path %> <br>
        </div>
    <% end %>


    <% if can? :index, Warehousing %>
        <div class="image">
          <%= link_to image_tag("Warehouse_With_Boxes-512.png", height: '50', alt:"Rohölbestand logo"), warehousings_path %><br>
          <%= link_to 'Anzeige der Rohölbestände', warehousings_path %> <br>
        </div>
    <% end %>


    <% if can? :index, Administration %>
        <div class="image">
          <%= link_to image_tag("produktionsparameter.png", height: '50', alt:"Produktionsparameter logo"), administrations_path %><br>
          <%= link_to 'Verwaltung der Produktionsparameter', administrations_path %> <br>
        </div>
    <% end %>


    <% if can? :index, GamsPath %>
        <div class="image">
          <%= link_to image_tag("gams.png", height: '50', alt:"GAMS logo"), gams_paths_path %><br>
          <%= link_to 'Verwaltung des GAMS-Pfads', gams_paths_path %> <br>
        </div>
    <% end %>
  </div>

  <% if can? :optimize, Warehousing%>
      <div class = "button">
        <%= button_to "Lösche den Produktions- und Lagerplan", {:controller => 'warehousings', :action => 'delete_old_plan'}, {:class => "btn btn-primary"} %> <br><br>
        <%= button_to "Optimierung starten und Ergebnisse einlesen", {:controller => 'warehousings', :action => 'optimize' }, {:class => "btn btn-primary"} %> <br><br>
      </div>
  <% end %>
</div>
<br><br><br>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> <h1>Kontakt</h1>
<p>Bei Fragen und Anregungen wenden Sie sich bitte per e-Mail an
  <%= mail_to("j.broihan@gmx.de", "Justine Broihan", :style=> "font-weight: bold")%>
  oder <%= mail_to("max-moeller91@web.de", "Max Möller", :style=> "font-weight: bold")%>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Hilfe</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help
    section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Herzlich Willkommen zur Blending-Oil-App</h1>

  <h2>
    Sie befinden sich auf der Homepage des
    <a href="https://www.gams.com/modlib/libhtml/food.htm">Blending of Oil Problems</a>.
  </h2>

  <% if not logged_in? %>
      <%= link_to "Jetzt kostenlos registrieren!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/mlclsp_start.html.erb
<% provide(:title, 'Losgrößenplanung') %>
<h1>Mehrstufige Losgrößenplanung mit dem MLCLSP</h1>
<p>
Auf dieser Seite startet die Losgrößenplanung!    <br>     <br>

  <%= link_to "Hier geht es zur Verwaltung der Produkte!", products_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Machinen!", machines_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Produkte-Produkte-Relationen!", product_product_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Produkte-Perioden-Relationen!", product_period_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Maschinen-Perioden-Relationen!", machine_period_associations_path %><br>
</p>

<br>


<% if logged_in? %>

    <p>

      Nach der Eingabe der Daten können wir nun endlich optimieren!

      <%= button_to "Lösche den Produktions- und Lagerplan", :controller => 'product_period_associations', :action => 'delete_old_plan' %>
      <%= button_to "Optimiere", :controller => 'product_period_associations', :action => 'optimize' %>
      <%= button_to "Lies die Ergebnisse ein", :controller => 'product_period_associations', :action => 'read_optimization_results' %>
      <%= button_to "Lies den Zielfunktionswert ein", :controller => 'product_period_associations', :action => 'read_and_show_ofv' %>

    </p>

<% end %>

app/views/static_pages/transport_start.html.erb
<% provide(:title, 'Transportplanung') %>
<h1>Klassisches Transportmodell</h1>
<p>
Auf dieser Seite startet die Transportplanung!    <br>     <br>

<%= link_to "Hier geht es zur Verwaltung der Orte!", sites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Angebotsdaten!", supplysites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Nachfragedaten!", demandsites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Transportrelationen!", translinks_path %><br>
</p>

<br>


<% if logged_in? %>



<p>

Nach der Eingabe der Daten können wir nun endlich optimieren!

  <%= button_to "Lösche Transportmengen", :controller => 'translinks', :action =>  'delete_transportation_quantities'  %>
  <%= button_to "Optimiere", :controller => 'translinks', :action =>  'optimize'  %>
  <%= button_to "Lies die Transportmengen ein", :controller => 'translinks', :action =>  'read_transportation_quantities'  %>
  <%= button_to "Lies den Zielfunktionswert ein", :controller => 'translinks', :action =>  'read_and_show_ofv'  %>

</p>

<% end %>